###########
# site.title, site.url, site.author.name

title:   'GrepCharm'
author:
  name:  'GrepCharm'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /WebSlides
url:  'https://grepcharm.github.io/WebSlides/'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title/

exclude:
- README.md

safe: true
lsi: false
